server:
  port: 8088

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/mail?characterEncoding=utf8&useSSL=false&&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.163.com
    username: zonedx@163.com
    password: yourPassword
    default-encoding: UTF-8
    protocol: smtp


mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.zone.mailservice.pojo